name: loglytics
description: An efficient, user-friendly way to implement logs, analytics and crash reports into your projects.
version: 0.16.2
repository: https://github.com/appboypov/loglytics
homepage: https://github.com/appboypov/loglytics
issue_tracker: https://github.com/appboypov/loglytics/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
